---
title: "Replication of Scotland's Natural Capital Asset Index"
author: "Kate O'Hara"
date: "2026-01-06"
output: html_document
---

## Project Overview

**NatureScot** produces Scotland's Natural Capital Assets Index (NCAI), a national statistic updated on a yearly basis. This index is traditionally calculated using data from the **Habitats Map of Scotland (HabMoS)** within an Excel framework. 

To improve reproducibility and efficiency, we developed the `openNCAI` package. This script demonstrates how to replicate the NCAI to date by pulling information from the official NatureScot spreadsheet and processing it within the R environment.

---

## Setup and Replication

The following code block initializes the `openNCAI` package and begins the replication process.

```{r replication-script}
# Load the package
# library(openNCAI) 
library(dplyr)
library(tidyr)
library(tibble)
library(readr)
library(readxl)



# To demonstrate, we replicate Scotlands NCAI to date using 
# information from NatureScot's spreadsheet.

# [Your replication code goes here]
